#!/bin/bash
# Audio Generation Script for Shona Pronunciation
# Generated by Mudzidzisi AI

echo "Generating pronunciation audio for 15 Shona words..."

# mangwanani (good morning)
echo "Generating: mangwanani"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("mangwanani"));

# eSpeak version:
espeak "mangwanani" -s 150 -p 50 -w mangwanani_espeak.wav

# Festival version:
echo "mangwanani" | festival --tts --otype ulaw --ostype ulaw > mangwanani_festival.au

# masikati (good afternoon)
echo "Generating: masikati"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("masikati"));

# eSpeak version:
espeak "masikati" -s 150 -p 50 -w masikati_espeak.wav

# Festival version:
echo "masikati" | festival --tts --otype ulaw --ostype ulaw > masikati_festival.au

# manheru (good evening)
echo "Generating: manheru"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("manheru"));

# eSpeak version:
espeak "manheru" -s 150 -p 50 -w manheru_espeak.wav

# Festival version:
echo "manheru" | festival --tts --otype ulaw --ostype ulaw > manheru_festival.au

# bhazi (bus)
echo "Generating: bhazi"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("bhazi"));

# eSpeak version:
espeak "bhazi" -s 150 -p 50 -w bhazi_espeak.wav

# Festival version:
echo "bhazi" | festival --tts --otype ulaw --ostype ulaw > bhazi_festival.au

# svika (arrive)
echo "Generating: svika"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("svika"));

# eSpeak version:
espeak "svika" -s 150 -p 50 -w svika_espeak.wav

# Festival version:
echo "svika" | festival --tts --otype ulaw --ostype ulaw > svika_festival.au

# zvino (now)
echo "Generating: zvino"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("zvino"));

# eSpeak version:
espeak "zvino" -s 150 -p 50 -w zvino_espeak.wav

# Festival version:
echo "zvino" | festival --tts --otype ulaw --ostype ulaw > zvino_festival.au

# tsvaira (drive)
echo "Generating: tsvaira"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("tsvaira"));

# eSpeak version:
espeak "tsvaira" -s 150 -p 50 -w tsvaira_espeak.wav

# Festival version:
echo "tsvaira" | festival --tts --otype ulaw --ostype ulaw > tsvaira_festival.au

# kuudza (to tell)
echo "Generating: kuudza"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("kuudza"));

# eSpeak version:
espeak "kuudza" -s 150 -p 50 -w kuudza_espeak.wav

# Festival version:
echo "kuudza" | festival --tts --otype ulaw --ostype ulaw > kuudza_festival.au

# mbira (thumb piano)
echo "Generating: mbira"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("mbira"));

# eSpeak version:
espeak "mbira" -s 150 -p 50 -w mbira_espeak.wav

# Festival version:
echo "mbira" | festival --tts --otype ulaw --ostype ulaw > mbira_festival.au

# ndimi (you (plural))
echo "Generating: ndimi"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("ndimi"));

# eSpeak version:
espeak "ndimi" -s 150 -p 50 -w ndimi_espeak.wav

# Festival version:
echo "ndimi" | festival --tts --otype ulaw --ostype ulaw > ndimi_festival.au

# ngoma (drum)
echo "Generating: ngoma"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("ngoma"));

# eSpeak version:
espeak "ngoma" -s 150 -p 50 -w ngoma_espeak.wav

# Festival version:
echo "ngoma" | festival --tts --otype ulaw --ostype ulaw > ngoma_festival.au

# ndatenda (thank you)
echo "Generating: ndatenda"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("ndatenda"));

# eSpeak version:
espeak "ndatenda" -s 150 -p 50 -w ndatenda_espeak.wav

# Festival version:
echo "ndatenda" | festival --tts --otype ulaw --ostype ulaw > ndatenda_festival.au

# zvakanaka (fine/good)
echo "Generating: zvakanaka"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("zvakanaka"));

# eSpeak version:
espeak "zvakanaka" -s 150 -p 50 -w zvakanaka_espeak.wav

# Festival version:
echo "zvakanaka" | festival --tts --otype ulaw --ostype ulaw > zvakanaka_festival.au

# pamusoroi (excuse me)
echo "Generating: pamusoroi"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("pamusoroi"));

# eSpeak version:
espeak "pamusoroi" -s 150 -p 50 -w pamusoroi_espeak.wav

# Festival version:
echo "pamusoroi" | festival --tts --otype ulaw --ostype ulaw > pamusoroi_festival.au

# sara (remain)
echo "Generating: sara"
# Web version: Use browser console with:
# speechSynthesis.speak(new SpeechSynthesisUtterance("sara"));

# eSpeak version:
espeak "sara" -s 150 -p 50 -w sara_espeak.wav

# Festival version:
echo "sara" | festival --tts --otype ulaw --ostype ulaw > sara_festival.au

echo "Audio generation complete!"
echo "Generated files: *.wav, *.au"
echo "Use convert tools to standardize format if needed"
