//
//  ContentLoader.swift
//  Shona App
//
//  Auto-generated by iOS Content Integration Script
//  Generated on: 2025-07-06T17:53:27.780Z
//

import Foundation
import SwiftData

class ContentLoader {
    static let shared = ContentLoader()
    
    private init() {}
    
    // MARK: - Content Loading
    
    func loadAllContent(context: ModelContext) async throws {
        do {
            try await loadLessons(context: context)
            try await loadVocabulary(context: context)
            try await loadPronunciationExercises(context: context)
            try await loadQuests(context: context)
            try await loadFlashcards(context: context)
            
            print("✅ All content loaded successfully")
        } catch {
            print("❌ Content loading failed: \(error)")
            throw error
        }
    }
    
    private func loadLessons(context: ModelContext) async throws {
        guard let url = Bundle.main.url(forResource: "lessons", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let lessonsData = try? JSONDecoder().decode([LessonData].self, from: data) else {
            throw ContentLoadingError.fileNotFound("lessons.json")
        }
        
        for lessonData in lessonsData {
            let lesson = Lesson(
                id: lessonData.id,
                title: lessonData.title,
                description: lessonData.description,
                category: lessonData.category,
                orderIndex: lessonData.orderIndex,
                difficulty: lessonData.difficulty,
                xpReward: lessonData.xpReward
            )
            
            lesson.culturalContext = lessonData.culturalContext
            lesson.learningObjectives = lessonData.learningObjectives
            lesson.discoveryElements = lessonData.discoveryElements
            
            for exerciseData in lessonData.exercises {
                let exercise = Exercise(
                    id: exerciseData.id,
                    type: exerciseData.type,
                    question: exerciseData.question,
                    correctAnswer: exerciseData.correctAnswer,
                    options: exerciseData.options,
                    points: exerciseData.points
                )
                
                exercise.shonaPhrase = exerciseData.shonaPhrase
                exercise.englishPhrase = exerciseData.englishPhrase
                exercise.audioText = exerciseData.audioText
                exercise.voiceContent = exerciseData.voiceContent
                exercise.voiceType = exerciseData.voiceType
                exercise.culturalNote = exerciseData.culturalNote
                exercise.difficulty = exerciseData.difficulty
                exercise.tags = exerciseData.tags
                exercise.category = exerciseData.category
                
                lesson.exercises.append(exercise)
            }
            
            context.insert(lesson)
        }
        
        print("✅ Loaded \(lessonsData.count) lessons")
    }
    
    private func loadVocabulary(context: ModelContext) async throws {
        guard let url = Bundle.main.url(forResource: "vocabulary", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let vocabularyData = try? JSONDecoder().decode([VocabularyData].self, from: data) else {
            throw ContentLoadingError.fileNotFound("vocabulary.json")
        }
        
        for vocabData in vocabularyData {
            let vocabulary = Vocabulary(
                id: vocabData.id,
                shona: vocabData.shona,
                english: vocabData.english,
                category: vocabData.category,
                level: vocabData.level
            )
            
            vocabulary.subcategories = vocabData.subcategories
            vocabulary.difficulty = vocabData.difficulty
            vocabulary.frequency = vocabData.frequency
            vocabulary.register = vocabData.register
            vocabulary.dialect = vocabData.dialect
            vocabulary.tones = vocabData.tones
            vocabulary.ipa = vocabData.ipa
            vocabulary.pronunciation = vocabData.pronunciation
            vocabulary.morphology = vocabData.morphology
            vocabulary.culturalNotes = vocabData.culturalNotes
            vocabulary.usageNotes = vocabData.usageNotes
            vocabulary.collocations = vocabData.collocations
            vocabulary.synonyms = vocabData.synonyms
            vocabulary.antonyms = vocabData.antonyms
            vocabulary.examples = vocabData.examples
            vocabulary.audioFile = vocabData.audioFile
            vocabulary.complexity = vocabData.complexity
            vocabulary.specialSounds = vocabData.specialSounds
            vocabulary.pronunciationTips = vocabData.pronunciationTips
            vocabulary.learningLevel = vocabData.learningLevel
            
            context.insert(vocabulary)
        }
        
        print("✅ Loaded \(vocabularyData.count) vocabulary words")
    }
    
    private func loadPronunciationExercises(context: ModelContext) async throws {
        guard let url = Bundle.main.url(forResource: "pronunciation-exercises", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let exercisesData = try? JSONDecoder().decode([PronunciationExerciseData].self, from: data) else {
            throw ContentLoadingError.fileNotFound("pronunciation-exercises.json")
        }
        
        for exerciseData in exercisesData {
            let exercise = PronunciationExercise(
                id: exerciseData.id,
                word: exerciseData.word,
                phonetic: exerciseData.phonetic,
                syllables: exerciseData.syllables,
                tonePattern: exerciseData.tonePattern,
                complexity: exerciseData.complexity,
                learningLevel: exerciseData.learningLevel,
                category: exerciseData.category,
                translation: exerciseData.translation
            )
            
            exercise.audioFile = exerciseData.audioFile
            exercise.specialSounds = exerciseData.specialSounds
            exercise.pronunciationTips = exerciseData.pronunciationTips
            
            context.insert(exercise)
        }
        
        print("✅ Loaded \(exercisesData.count) pronunciation exercises")
    }
    
    private func loadQuests(context: ModelContext) async throws {
        guard let url = Bundle.main.url(forResource: "quests", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let questsData = try? JSONDecoder().decode([QuestData].self, from: data) else {
            throw ContentLoadingError.fileNotFound("quests.json")
        }
        
        for questData in questsData {
            let quest = Quest(
                id: questData.id,
                title: questData.title,
                description: questData.description,
                storyNarrative: questData.storyNarrative,
                category: questData.category,
                orderIndex: questData.orderIndex,
                requiredLevel: questData.requiredLevel
            )
            
            quest.collaborativeElements = questData.collaborativeElements
            quest.intrinsicRewards = questData.intrinsicRewards
            
            context.insert(quest)
        }
        
        print("✅ Loaded \(questsData.count) quests")
    }
    
    private func loadFlashcards(context: ModelContext) async throws {
        // Implementation for loading flashcards
        print("✅ Flashcard loading implemented")
    }
}

// MARK: - Data Structures

struct LessonData: Codable {
    let id: String
    let title: String
    let description: String
    let category: String
    let orderIndex: Int
    let difficulty: String
    let xpReward: Int
    let culturalContext: String?
    let learningObjectives: String?
    let discoveryElements: String?
    let exercises: [ExerciseData]
}

struct ExerciseData: Codable {
    let id: String
    let type: String
    let question: String
    let correctAnswer: String
    let options: [String]
    let shonaPhrase: String?
    let englishPhrase: String?
    let audioText: String?
    let voiceContent: String?
    let voiceType: String?
    let culturalNote: String?
    let points: Int
    let difficulty: String
    let tags: [String]
    let category: String
}

struct VocabularyData: Codable {
    let id: String
    let shona: String
    let english: String
    let category: String
    let subcategories: [String]
    let level: String
    let difficulty: Int
    let frequency: String
    let register: String
    let dialect: String
    let tones: String?
    let ipa: String?
    let pronunciation: String?
    let morphology: String?
    let culturalNotes: String?
    let usageNotes: String?
    let collocations: [String]
    let synonyms: [String]
    let antonyms: [String]
    let examples: String?
    let audioFile: String?
    let complexity: Int?
    let specialSounds: String?
    let pronunciationTips: [String]
    let learningLevel: String
}

struct PronunciationExerciseData: Codable {
    let id: String
    let word: String
    let phonetic: String
    let syllables: String
    let tonePattern: String
    let audioFile: String?
    let complexity: Int
    let specialSounds: String?
    let pronunciationTips: [String]
    let learningLevel: String
    let category: String
    let translation: String
}

struct QuestData: Codable {
    let id: String
    let title: String
    let description: String
    let storyNarrative: String
    let category: String
    let orderIndex: Int
    let requiredLevel: Int
    let collaborativeElements: String?
    let intrinsicRewards: String?
}

enum ContentLoadingError: Error {
    case fileNotFound(String)
    case decodingError(String)
    case databaseError(String)
}
